name: Build & Push to Azure ACR

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

env:
  ACR_NAME: findistressai                 # <-- your ACR short name (no .azurecr.io)
  IMAGE_NAME: financial-distress-api
  IMAGE_TAG: latest                       # or use ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Dockerfile if missing
        run: |
          if [ ! -f Dockerfile ]; then
            cat > Dockerfile <<'EOF'
      FROM python:3.11-slim
      ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
      WORKDIR /app
      COPY requirements.txt /app/ 2>/dev/null || true
      RUN if [ -f requirements.txt ]; then \
            pip install --no-cache-dir -r requirements.txt ; \
          else \
            pip install --no-cache-dir fastapi uvicorn[standard] lightgbm shap scikit-learn pandas joblib python-dotenv ; \
          fi
      COPY . /app
      EXPOSE 8000
      CMD ["bash","-lc","uvicorn app.main:app --host 0.0.0.0 --port 8000 || uvicorn main:app --host 0.0.0.0 --port 8000"]
      EOF
          fi

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build & Push image
        run: |
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
